name: CI/CD Pipeline for NASA Flask App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set Docker image version (using Git commit hash)
        id: set_version
        run: |
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "NEW_VERSION=$GIT_COMMIT_HASH" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:latest -t ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:$NEW_VERSION .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:$NEW_VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Clone the Helm Chart repository
        run: |
          #git clone https://github.com/Kuper-S/nasa-helm-charts.git
          git clone -c user.name="CI Bot" -c user.email="ci-bot@example.com" https://github.com/Kuper-S/nasa-helm-charts.git
          cd nasa-helm-charts
        env:
          GITHUB_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}


      - name: Update Docker Image Version in Helm Chart
        run: |
          pwd
          ls -la
          yq eval '.image.tag = env(NEW_VERSION)' -i ./values.yaml
          git add .
          git commit -m "Update image tag to $NEW_VERSION"
          git push
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Commit and Push Helm Chart Changes
        run: |
          git commit -m "Update image tag to $NEW_VERSION"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}















