name: CI/CD Pipeline for NASA Flask App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set Docker image version (using Git commit hash)
        id: set_version
        run: |
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          NEW_VERSION="1.0.${GIT_COMMIT_HASH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          #echo "The new version is: $NEW_VERSION"
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:latest -t ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:$NEW_VERSION .

      - name: Install Trivy
        run: |
          sudo apt-get install wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.31.3/trivy_0.31.3_Linux-64bit.deb
          sudo dpkg -i trivy_0.31.3_Linux-64bit.deb

      - name: Run Trivy Image Scan
        run: |
          trivy image --download-db-only

          trivy image --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:$NEW_VERSION
        continue-on-error: true

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nasa-flask-app:$NEW_VERSION
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}


      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.6/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Clone the Helm Chart repository
        run: |
          #git clone https://github.com/Kuper-S/nasa-helm-charts.git
          git clone -c user.name="CI Bot" -c user.email="ci-bot@example.com" https://github.com/Kuper-S/nasa-helm-charts.git
          cd nasa-helm-charts
        env:
          HELM_REPO_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}

      - name: Update Docker Image Version in Helm Chart
        run: |
          cd nasa-helm-charts  # Move into the correct repo
          VALUES_FILE=$(find . -name "values.yaml")  # Find the values.yaml file
          echo "Updating image tag in $VALUES_FILE to $NEW_VERSION"
          yq e '.image.tag = strenv(NEW_VERSION)' -i $VALUES_FILE  # Update the image tag

          # Configure Git user information for committing
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"

          git add $VALUES_FILE
          git commit -m "Update image tag to $NEW_VERSION"
          git push https://x-access-token:${{ secrets.HELM_REPO_TOKEN }}@github.com/Kuper-S/nasa-helm-charts.git
        env:
          NEW_VERSION: ${{ env.NEW_VERSION }}
          HELM_REPO_TOKEN: ${{ secrets.HELM_REPO_TOKEN }}














